// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRLGhjaHmFg7wz3ROJiarv709qVid9Ve0',
    appId: '1:427866789049:web:b45f58ccda977e6f093768',
    messagingSenderId: '427866789049',
    projectId: 'clasc-6694d',
    authDomain: 'clasc-6694d.firebaseapp.com',
    storageBucket: 'clasc-6694d.appspot.com',
    measurementId: 'G-4DBLJ3KG0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpP_zH-xc_f0go9aSmIePY3xSZGwL7DmM',
    appId: '1:427866789049:android:54d5e33a757421aa093768',
    messagingSenderId: '427866789049',
    projectId: 'clasc-6694d',
    storageBucket: 'clasc-6694d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALLJ4YPaJoffrmGA9lwHVKoXRdUDOUtO8',
    appId: '1:427866789049:ios:3cd4085c2b5a6984093768',
    messagingSenderId: '427866789049',
    projectId: 'clasc-6694d',
    storageBucket: 'clasc-6694d.appspot.com',
    androidClientId: '427866789049-183c0p00u92p00mvr1u3k8e92l16kgs4.apps.googleusercontent.com',
    iosClientId: '427866789049-buv5ha62p30hakauo296fbat2lkjvkt7.apps.googleusercontent.com',
    iosBundleId: 'com.clasc',
  );
}
